<?php
/**
 * ArticleBenefitsDnsEditorTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Mittwald\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Public API
 *
 * Schnittstellen für Mittwald-Kunden
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.9
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Mittwald\Api;

/**
 * ArticleBenefitsDnsEditorTest Class Doc Comment
 *
 * @category    Class
 * @description ArticleBenefitsDnsEditor
 * @package     Mittwald\Api
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ArticleBenefitsDnsEditorTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ArticleBenefitsDnsEditor"
     */
    public function testArticleBenefitsDnsEditor()
    {
    }

    /**
     * Test attribute "active"
     */
    public function testPropertyActive()
    {
    }

    /**
     * Test attribute "editor_a"
     */
    public function testPropertyEditorA()
    {
    }

    /**
     * Test attribute "editor_cname"
     */
    public function testPropertyEditorCname()
    {
    }

    /**
     * Test attribute "editor_mx"
     */
    public function testPropertyEditorMx()
    {
    }

    /**
     * Test attribute "editor_srv"
     */
    public function testPropertyEditorSrv()
    {
    }

    /**
     * Test attribute "editor_txt"
     */
    public function testPropertyEditorTxt()
    {
    }
}
