<?php
/**
 * ArticleBenefitsServerHardwareTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Mittwald\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Public API
 *
 * Schnittstellen für Mittwald-Kunden
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Mittwald\Api;

/**
 * ArticleBenefitsServerHardwareTest Class Doc Comment
 *
 * @category    Class */
// * @description ArticleBenefitsServerHardware
/**
 * @package     Mittwald\Api
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ArticleBenefitsServerHardwareTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ArticleBenefitsServerHardware"
     */
    public function testArticleBenefitsServerHardware()
    {
    }

    /**
     * Test attribute "max_webspace"
     */
    public function testPropertyMaxWebspace()
    {
    }

    /**
     * Test attribute "v_cpu_cores"
     */
    public function testPropertyVCpuCores()
    {
    }

    /**
     * Test attribute "v_cpu_units"
     */
    public function testPropertyVCpuUnits()
    {
    }

    /**
     * Test attribute "v_max_memory"
     */
    public function testPropertyVMaxMemory()
    {
    }

    /**
     * Test attribute "v_max_traffic"
     */
    public function testPropertyVMaxTraffic()
    {
    }

    /**
     * Test attribute "memory_limit"
     */
    public function testPropertyMemoryLimit()
    {
    }

    /**
     * Test attribute "max_execution_time"
     */
    public function testPropertyMaxExecutionTime()
    {
    }
}
