<?php
/**
 * CustomerContractTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Mittwald\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Public API
 *
 * Schnittstellen für Mittwald-Kunden
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Mittwald\Api;

/**
 * CustomerContractTest Class Doc Comment
 *
 * @category    Class */
// * @description CustomerContract
/**
 * @package     Mittwald\Api
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CustomerContractTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CustomerContract"
     */
    public function testCustomerContract()
    {
    }

    /**
     * Test attribute "uid"
     */
    public function testPropertyUid()
    {
    }

    /**
     * Test attribute "article"
     */
    public function testPropertyArticle()
    {
    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {
    }

    /**
     * Test attribute "text"
     */
    public function testPropertyText()
    {
    }

    /**
     * Test attribute "source_uid"
     */
    public function testPropertySourceUid()
    {
    }

    /**
     * Test attribute "source_type"
     */
    public function testPropertySourceType()
    {
    }

    /**
     * Test attribute "creation_date"
     */
    public function testPropertyCreationDate()
    {
    }

    /**
     * Test attribute "next_period_date"
     */
    public function testPropertyNextPeriodDate()
    {
    }

    /**
     * Test attribute "cancellation"
     */
    public function testPropertyCancellation()
    {
    }

    /**
     * Test attribute "account"
     */
    public function testPropertyAccount()
    {
    }
}
