<?php
/**
 * GDPRContractTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Mittwald\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Public API
 *
 * Schnittstellen für Mittwald-Kunden
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Mittwald\Api;

/**
 * GDPRContractTest Class Doc Comment
 *
 * @category    Class */
// * @description GDPRContract
/**
 * @package     Mittwald\Api
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GDPRContractTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "GDPRContract"
     */
    public function testGDPRContract()
    {
    }

    /**
     * Test attribute "creation_date"
     */
    public function testPropertyCreationDate()
    {
    }

    /**
     * Test attribute "tom"
     */
    public function testPropertyTom()
    {
    }

    /**
     * Test attribute "client"
     */
    public function testPropertyClient()
    {
    }

    /**
     * Test attribute "recipient"
     */
    public function testPropertyRecipient()
    {
    }

    /**
     * Test attribute "html"
     */
    public function testPropertyHtml()
    {
    }

    /**
     * Test attribute "confirmation_date"
     */
    public function testPropertyConfirmationDate()
    {
    }

    /**
     * Test attribute "sent_date"
     */
    public function testPropertySentDate()
    {
    }

    /**
     * Test attribute "reminder_sent_date"
     */
    public function testPropertyReminderSentDate()
    {
    }

    /**
     * Test attribute "is_partner_contract"
     */
    public function testPropertyIsPartnerContract()
    {
    }

    /**
     * Test attribute "contract_signer"
     */
    public function testPropertyContractSigner()
    {
    }
}
