<?php
/**
 * DSGVOTOMsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Mittwald\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Public API
 *
 * Schnittstellen für Mittwald-Kunden
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.20
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Mittwald\Api;

use \Mittwald\Api\Configuration;
use \Mittwald\Api\ApiException;
use \Mittwald\Api\ObjectSerializer;

/**
 * DSGVOTOMsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Mittwald\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DSGVOTOMsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createGDPRTom
     *
     * TOM - TOM anlegen.
     *
     */
    public function testCreateGDPRTom()
    {
    }

    /**
     * Test case for getGDPRTom
     *
     * TOM - Liefert einen bestimmten TOM.
     *
     */
    public function testGetGDPRTom()
    {
    }

    /**
     * Test case for getGDPRToms
     *
     * TOM - Liefert alle hinterlegten TOMs.
     *
     */
    public function testGetGDPRToms()
    {
    }
}
