<?php
/**
 * TicketsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Mittwald\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Public API
 *
 * Schnittstellen für Mittwald-Kunden
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.20
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Mittwald\Api;

use \Mittwald\Api\Configuration;
use \Mittwald\Api\ApiException;
use \Mittwald\Api\ObjectSerializer;

/**
 * TicketsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Mittwald\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TicketsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for answerSupportTicket
     *
     * Ticketantwort erstellen.
     *
     */
    public function testAnswerSupportTicket()
    {
    }

    /**
     * Test case for createSupportTicket
     *
     * Neues Support-Ticket.
     *
     */
    public function testCreateSupportTicket()
    {
    }

    /**
     * Test case for listSupportTicketAnswers
     *
     * Ticketantworten auslesen.
     *
     */
    public function testListSupportTicketAnswers()
    {
    }

    /**
     * Test case for listSupportTickets
     *
     * Support-Tickets auslesen.
     *
     */
    public function testListSupportTickets()
    {
    }
}
