<?php
/**
 * WarenkorbApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Mittwald\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Public API
 *
 * Schnittstellen für Mittwald-Kunden
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Mittwald\Api;

use \Mittwald\Api\Configuration;
use \Mittwald\Api\ApiException;
use \Mittwald\Api\ObjectSerializer;

/**
 * WarenkorbApiTest Class Doc Comment
 *
 * @category Class
 * @package  Mittwald\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class WarenkorbApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for addDomainToCart
     *
     * Warenkorb-Domainposition hinzufügen.
     *
     */
    public function testAddDomainToCart()
    {
    }

    /**
     * Test case for addItemToCart
     *
     * Warenkorb-Position hinzufügen.
     *
     */
    public function testAddItemToCart()
    {
    }

    /**
     * Test case for checkoutOrder
     *
     * Bestellung abschließen.
     *
     */
    public function testCheckoutOrder()
    {
    }

    /**
     * Test case for confirmSMSVerification
     *
     * SMS-Verifizierung bestätigen.
     *
     */
    public function testConfirmSMSVerification()
    {
    }

    /**
     * Test case for createCart
     *
     * Warenkorb erstellen.
     *
     */
    public function testCreateCart()
    {
    }

    /**
     * Test case for createCartFromTemplate
     *
     * Warenkorb aus Vorlage erstellen.
     *
     */
    public function testCreateCartFromTemplate()
    {
    }

    /**
     * Test case for createQuoteFromCart
     *
     * Angebot versenden.
     *
     */
    public function testCreateQuoteFromCart()
    {
    }

    /**
     * Test case for deleteCart
     *
     * Warenkorb löschen.
     *
     */
    public function testDeleteCart()
    {
    }

    /**
     * Test case for deleteItemFromCart
     *
     * Warenkorb-Position löschen.
     *
     */
    public function testDeleteItemFromCart()
    {
    }

    /**
     * Test case for getCart
     *
     * Warenkorb auslesen.
     *
     */
    public function testGetCart()
    {
    }

    /**
     * Test case for requestSMSVerification
     *
     * SMS-Verifizierung starten.
     *
     */
    public function testRequestSMSVerification()
    {
    }

    /**
     * Test case for shareCart
     *
     * Warenkorbvorlage erstellen.
     *
     */
    public function testShareCart()
    {
    }

    /**
     * Test case for updateCart
     *
     * Warenkorb bearbeiten.
     *
     */
    public function testUpdateCart()
    {
    }
}
